[package]
version = "0.1.0"
name = "mcalendar_client"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dev-dependencies]
wasm-bindgen-test = "0.3.18"

[dependencies]
seed = "0.8.0"
mcalendar_shared = { path = "../shared" }