# IP address
address = "0.0.0.0"

# port to listen on
port = 8000

# sled file location
sled = "./mcalendar.sled"

# templates (handlebars) location
templates = "./templates"

# static files location
wwwroot = "./static"
