# IP address
address = "0.0.0.0"

# port to listen on
port = 8000

# sled file location
sled = "/var/mcalendar/mcalendar.sled"

# templates (handlebars) location
templates = "/var/mcalendar/templates"

# static files location
wwwroot = "/var/mcalendar/static"
