[package]
name = "server"
version = "0.1.0"
edition = "2018"
build = "build.rs"

[build-dependencies]
actix-web-static-files = "3.0"

[dependencies]
#actix = "4"
actix-web = "3.1"
actix-rt = "1.1"
actix-web-static-files = "3.0"
#tokio = { version = "0.3", features = ["full"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0"

chrono = "0.4"
#reqwest = "0.11"

shared = { path = "../shared" }